services:
  typesense:
    image: typesense/typesense:0.24.0.rcn56
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: S3CR3T
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8108/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - typesense-data:/data

volumes:
  typesense-data:
