schranz_search:
    schemas:
        algolia:
            dir: '%kernel.project_dir%/config/schemas'
            engine: algolia
        elasticsearch:
            dir: '%kernel.project_dir%/config/schemas'
            engine: elasticsearch
        meilisearch:
            dir: '%kernel.project_dir%/config/schemas'
            engine: meilisearch
        memory:
            dir: '%kernel.project_dir%/config/schemas'
            engine: memory
        opensearch:
            dir: '%kernel.project_dir%/config/schemas'
            engine: opensearch
        redisearch:
            dir: '%kernel.project_dir%/config/schemas'
            engine: redisearch
        solr:
            dir: '%kernel.project_dir%/config/schemas'
            engine: solr
        typesense:
            dir: '%kernel.project_dir%/config/schemas'
            engine: typesense
    engines:
        algolia:
            adapter: 'algolia://%env(ALGOLIA_APPLICATION_ID)%:%env(ALGOLIA_ADMIN_API_KEY)%'
        elasticsearch:
            adapter: 'elasticsearch://127.0.0.1:9200'
        meilisearch:
            adapter: 'meilisearch://127.0.0.1:7700'
        memory:
            adapter: 'memory://'
        opensearch:
            adapter: 'opensearch://127.0.0.1:9201'
        redisearch:
            adapter: 'redis://supersecure@127.0.0.1:6379'
        solr:
            adapter: 'solr://127.0.0.1:8983'
        typesense:
            adapter: 'typesense://S3CR3T@127.0.0.1:8108'

        # ...
        multi:
            adapter: 'multi://elasticsearch?adapters[]=opensearch'
        read-write:
            adapter: 'read-write://elasticsearch?write=multi'
