name: Callable Test

on:
    workflow_call:
        inputs:
            directory:
                required: true
                type: string

jobs:
    test:
        name: "PHP ${{ matrix.php-version }}"
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '8.1'
                      dependency-versions: 'lowest'

                    - php-version: '8.2'
                      dependency-versions: 'highest'

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2'
                  ini-values: memory_limit=-1
                  coverage: none

            - name: Require @dev packages
              working-directory: ${{ inputs.directory }}
              run: |
                  composer require schranz-search/seal:"@dev"

            - name: Install composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: ${{ inputs.directory }}
                  dependency-versions: ${{matrix.dependency-versions}}

            - name: Run tests
              run: vendor/bin/phpunit
              working-directory: ${{ inputs.directory }}
