name: Docs

on:
    pull_request_target:
    push:
        branches:
            - '[0-9]+.[0-9]+'

permissions:
    contents: write

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: "${{ github.event.pull_request.merge_commit_sha }}"
            - uses: actions/setup-python@v3
            - name: Install dependencies
              run: |
                  pip install -r docs/requirements.txt

            - name: Sphinx build
              run: |
                  sphinx-build docs docs/_build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/0.1' }}
              with:
                  publish_branch: gh-pages
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/_build/
                  force_orphan: true
