name: Test

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'

jobs:
    memory-adapter:
        name: Memory Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-memory-adapter'
            docker: false

    elasticsearch-adapter:
        name: Elasticsearch Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-elasticsearch-adapter'
            docker: true
