name: Test

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'

jobs:
    seal-core:
        name: SEAL Core
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal'
            docker: false

    memory-adapter:
        name: Memory Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-memory-adapter'
            docker: false

    elasticsearch-adapter:
        name: Elasticsearch Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-elasticsearch-adapter'
            docker: true

    opensearch-adapter:
        name: Opensearch Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-opensearch-adapter'
            docker: true

    meilisearch-adapter:
        name: Meilisearch Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-meilisearch-adapter'
            docker: true

    algolia-adapter:
        name: Algolia Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-algolia-adapter'
            docker: false
        secrets: inherit

    redisearch-adapter:
        name: RediSearch Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-redisearch-adapter'
            docker: true
        secrets: inherit

    solr-adapter:
        name: Solr Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-solr-adapter'
            docker: true
        secrets: inherit

    typesense-adapter:
        name: Typesense Adapter
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: 'packages/seal-typesense-adapter'
            docker: true

    symfony-integration-example:
        name: Symfony Integration Example
        uses: ./.github/workflows/callable-test.yml
        with:
            directory: '.examples/symfony'
            docker: true
        secrets: inherit
